import type { AktauPortOperations, DetectionEvent, InvestigationNetwork, MaritimeEvent, Port, RiskAssessment, TrackPoint, TrackingEvent, Vessel, Voyage, VoyageIntelligence } from './types'

export const vessels: Vessel[] = [
  { id:'caspian-star', imo:'9384721', mmsi:'436000118', name:'CASPIAN STAR', type:'Cargo vessel', flag:'Kazakhstan', flagCode:'KZ', length:142, width:21, deadweight:11820, owner:'Caspian Marine Co.', operator:'Caspian Marine Co.', latitude:42.31, longitude:50.74, x:61, y:33, speed:12.4, course:47, heading:49, draught:4.8, destination:'Aktau', reportedEta:'15:05', calculatedEta:'15:12', navigationStatus:'Underway', lastPositionAt:'2 min ago', risk:91, riskLevel:'CRITICAL', riskUpdatedAt:'17:46' },
  { id:'khazar-wave', imo:'9261840', mmsi:'423000712', name:'KHAZAR WAVE', type:'Oil tanker', flag:'Azerbaijan', flagCode:'AZ', length:155, width:24, deadweight:13400, owner:'Khazar Shipping', operator:'ASCO', latitude:40.82, longitude:50.21, x:49, y:61, speed:9.8, course:344, heading:341, draught:6.2, destination:'Baku', reportedEta:'18:40', calculatedEta:'18:47', navigationStatus:'Underway', lastPositionAt:'4 min ago', risk:28, riskLevel:'MODERATE', riskUpdatedAt:'17:34' },
  { id:'volga-marine', imo:'9142202', mmsi:'273451810', name:'VOLGA MARINE', type:'General cargo', flag:'Russia', flagCode:'RU', length:128, width:18, deadweight:7900, owner:'Volga Fleet', operator:'Volga Fleet', latitude:43.16, longitude:48.91, x:36, y:22, speed:7.1, course:158, heading:160, draught:3.9, destination:'Makhachkala', reportedEta:'21:30', calculatedEta:'21:25', navigationStatus:'Underway', lastPositionAt:'1 min ago', risk:8, riskLevel:'LOW', riskUpdatedAt:'17:39' },
  { id:'turkmen-breeze', imo:'9501127', mmsi:'434120901', name:'TURKMEN BREEZE', type:'Ro-Ro cargo', flag:'Turkmenistan', flagCode:'TM', length:135, width:20, deadweight:9600, owner:'Turkmen Sea Lines', operator:'Turkmen Sea Lines', latitude:40.20, longitude:52.61, x:73, y:67, speed:0, course:0, heading:88, draught:4.4, destination:'Turkmenbashi', reportedEta:'Arrived', calculatedEta:'Arrived', navigationStatus:'Moored', lastPositionAt:'7 min ago', risk:4, riskLevel:'LOW', riskUpdatedAt:'17:32' },
  { id:'anzali-trader', imo:'9413344', mmsi:'422034500', name:'ANZALI TRADER', type:'Container ship', flag:'Iran', flagCode:'IR', length:149, width:23, deadweight:12100, owner:'Caspian Trade Line', operator:'IRISL', latitude:38.72, longitude:50.51, x:53, y:86, speed:10.6, course:352, heading:350, draught:5.7, destination:'Anzali', reportedEta:'11:20', calculatedEta:'11:36', navigationStatus:'Underway', lastPositionAt:'5 min ago', risk:19, riskLevel:'LOW', riskUpdatedAt:'17:31' },
  { id:'aktau-merchant', imo:'9326101', mmsi:'436000991', name:'AKTAU MERCHANT', type:'Bulk carrier', flag:'Kazakhstan', flagCode:'KZ', length:151, width:23, deadweight:14800, owner:'KazSea Transport', operator:'KazSea Transport', latitude:43.22, longitude:51.11, x:66, y:18, speed:0.4, course:211, heading:208, draught:6.1, destination:'Kuryk', reportedEta:'16:50', calculatedEta:'16:55', navigationStatus:'At anchor', lastPositionAt:'3 min ago', risk:7, riskLevel:'LOW', riskUpdatedAt:'17:37' },
  { id:'turan', imo:'9217748', mmsi:'423001108', name:'TURAN', type:'General cargo', flag:'Azerbaijan', flagCode:'AZ', length:118, width:18, deadweight:7200, owner:'Turan Maritime Services', operator:'Turan Maritime Services', latitude:42.04, longitude:50.61, x:60, y:33, speed:0.4, course:224, heading:226, draught:4.6, destination:'Baku', reportedEta:'22:10', calculatedEta:'22:28', navigationStatus:'Stopped', lastPositionAt:'1 min ago', risk:71, riskLevel:'HIGH', riskUpdatedAt:'17:42' },
  { id:'baku-express', imo:'9451180', mmsi:'423002184', name:'BAKU EXPRESS', type:'Ro-Ro cargo', flag:'Azerbaijan', flagCode:'AZ', length:154, width:24, deadweight:10900, owner:'Baku Ferry Lines', operator:'Baku Ferry Lines', latitude:40.92, longitude:50.18, x:44, y:55, speed:8.9, course:31, heading:33, draught:5.2, destination:'Kuryk', reportedEta:'02:40', calculatedEta:'03:12', navigationStatus:'Underway', lastPositionAt:'2 min ago', risk:63, riskLevel:'HIGH', riskUpdatedAt:'17:22' },
  { id:'caspian-wind', imo:'9347014', mmsi:'434001702', name:'CASPIAN WIND', type:'Cargo vessel', flag:'Turkmenistan', flagCode:'TM', length:132, width:19, deadweight:8450, owner:'Turkmen Logistics Fleet', operator:'Turkmen Logistics Fleet', latitude:41.35, longitude:52.18, x:69, y:62, speed:6.4, course:318, heading:315, draught:4.9, destination:'Aktau', reportedEta:'04:25', calculatedEta:'04:48', navigationStatus:'Underway', lastPositionAt:'6 min ago', risk:51, riskLevel:'HIGH', riskUpdatedAt:'17:18' },
  { id:'derbent-voyager', imo:'9198421', mmsi:'273452114', name:'DERBENT VOYAGER', type:'General cargo', flag:'Russia', flagCode:'RU', length:121, width:17, deadweight:6800, owner:'Dagestan Marine', operator:'Dagestan Marine', latitude:42.12, longitude:48.12, x:27, y:46, speed:8.2, course:167, heading:165, draught:3.8, destination:'Baku', reportedEta:'23:55', calculatedEta:'00:14', navigationStatus:'Underway', lastPositionAt:'3 min ago', risk:36, riskLevel:'MODERATE', riskUpdatedAt:'17:29' },
  { id:'aral-pioneer', imo:'9483200', mmsi:'436001206', name:'ARAL PIONEER', type:'Bulk carrier', flag:'Kazakhstan', flagCode:'KZ', length:164, width:25, deadweight:16200, owner:'KazBulk Shipping', operator:'KazBulk Shipping', latitude:43.76, longitude:50.02, x:47, y:14, speed:5.7, course:104, heading:102, draught:6.4, destination:'Aktau', reportedEta:'20:15', calculatedEta:'20:34', navigationStatus:'Underway', lastPositionAt:'8 min ago', risk:22, riskLevel:'LOW', riskUpdatedAt:'17:26' },
  { id:'makhachkala-star', imo:'9365208', mmsi:'273456702', name:'MAKHACHKALA STAR', type:'Oil products tanker', flag:'Russia', flagCode:'RU', length:146, width:22, deadweight:12400, owner:'CaspOil Fleet', operator:'CaspOil Fleet', latitude:42.68, longitude:48.02, x:25, y:38, speed:0, course:0, heading:91, draught:5.9, destination:'Makhachkala', reportedEta:'Arrived', calculatedEta:'Arrived', navigationStatus:'Moored', lastPositionAt:'4 min ago', risk:12, riskLevel:'LOW', riskUpdatedAt:'17:35' },
  { id:'absheron-spirit', imo:'9521844', mmsi:'423003417', name:'ABSHERON SPIRIT', type:'Offshore supply', flag:'Azerbaijan', flagCode:'AZ', length:82, width:16, deadweight:3200, owner:'Absheron Offshore', operator:'Absheron Offshore', latitude:40.16, longitude:50.47, x:51, y:68, speed:7.6, course:72, heading:70, draught:3.7, destination:'Alat', reportedEta:'19:30', calculatedEta:'19:38', navigationStatus:'Underway', lastPositionAt:'1 min ago', risk:17, riskLevel:'LOW', riskUpdatedAt:'17:40' },
  { id:'port-baku', imo:'9276417', mmsi:'423004126', name:'PORT BAKU', type:'Container ship', flag:'Azerbaijan', flagCode:'AZ', length:137, width:21, deadweight:9800, owner:'Azeri Container Line', operator:'Azeri Container Line', latitude:39.83, longitude:49.62, x:39, y:72, speed:0.2, course:12, heading:10, draught:5.1, destination:'Alat', reportedEta:'20:05', calculatedEta:'20:05', navigationStatus:'At anchor', lastPositionAt:'9 min ago', risk:9, riskLevel:'LOW', riskUpdatedAt:'17:20' },
  { id:'volga-pearl', imo:'9138627', mmsi:'273459885', name:'VOLGA PEARL', type:'River-sea cargo', flag:'Russia', flagCode:'RU', length:114, width:16, deadweight:5100, owner:'Lower Volga Shipping', operator:'Lower Volga Shipping', latitude:44.38, longitude:48.74, x:34, y:10, speed:6.8, course:151, heading:149, draught:3.5, destination:'Astrakhan', reportedEta:'05:40', calculatedEta:'05:58', navigationStatus:'Underway', lastPositionAt:'12 min ago', risk:26, riskLevel:'MODERATE', riskUpdatedAt:'17:15' },
  { id:'amirabad-cargo', imo:'9495174', mmsi:'422041806', name:'AMIRABAD CARGO', type:'General cargo', flag:'Iran', flagCode:'IR', length:141, width:22, deadweight:11200, owner:'Iran Caspian Cargo', operator:'Iran Caspian Cargo', latitude:37.52, longitude:52.68, x:66, y:90, speed:9.4, course:104, heading:106, draught:5.4, destination:'Amirabad', reportedEta:'07:20', calculatedEta:'07:37', navigationStatus:'Underway', lastPositionAt:'7 min ago', risk:14, riskLevel:'LOW', riskUpdatedAt:'17:27' },
  { id:'kuryk-ferry', imo:'9562082', mmsi:'436001874', name:'KURYK FERRY', type:'Rail ferry', flag:'Kazakhstan', flagCode:'KZ', length:151, width:26, deadweight:10500, owner:'KazFerry', operator:'KazFerry', latitude:43.33, longitude:51.49, x:70, y:24, speed:1.2, course:284, heading:281, draught:4.7, destination:'Kuryk', reportedEta:'18:10', calculatedEta:'18:16', navigationStatus:'At anchor', lastPositionAt:'2 min ago', risk:6, riskLevel:'LOW', riskUpdatedAt:'17:41' },
  { id:'caspian-horizon', imo:'9472603', mmsi:'434003008', name:'CASPIAN HORIZON', type:'Chemical tanker', flag:'Turkmenistan', flagCode:'TM', length:139, width:21, deadweight:11600, owner:'Hazar Deniz Fleet', operator:'Hazar Deniz Fleet', latitude:41.06, longitude:51.44, x:63, y:55, speed:10.1, course:332, heading:330, draught:5.6, destination:'Turkmenbashi', reportedEta:'01:15', calculatedEta:'01:29', navigationStatus:'Underway', lastPositionAt:'5 min ago', risk:33, riskLevel:'MODERATE', riskUpdatedAt:'17:33' },
  { id:'sari-trader', imo:'9395605', mmsi:'422046921', name:'SARI TRADER', type:'Dry cargo', flag:'Iran', flagCode:'IR', length:126, width:19, deadweight:7600, owner:'Mazandaran Shipping', operator:'Mazandaran Shipping', latitude:37.18, longitude:51.34, x:56, y:94, speed:8.7, course:271, heading:269, draught:4.3, destination:'Anzali', reportedEta:'09:45', calculatedEta:'10:02', navigationStatus:'Underway', lastPositionAt:'11 min ago', risk:18, riskLevel:'LOW', riskUpdatedAt:'17:17' },
]

export const ports: Port[] = [
  { id:'aktau', name:'Aktau', country:'Kazakhstan', latitude:43.65, longitude:51.16, x:72, y:28, vessels:12, status:'Operational' },
  { id:'kuryk', name:'Kuryk', country:'Kazakhstan', latitude:43.20, longitude:51.65, x:70, y:37, vessels:7, status:'Operational' },
  { id:'baku', name:'Baku', country:'Azerbaijan', latitude:40.37, longitude:49.89, x:35, y:60, vessels:24, status:'Busy' },
  { id:'alat', name:'Alat', country:'Azerbaijan', latitude:39.95, longitude:49.41, x:37, y:68, vessels:9, status:'Operational' },
  { id:'turkmenbashi', name:'Turkmenbashi', country:'Turkmenistan', latitude:40.02, longitude:52.97, x:77, y:64, vessels:11, status:'Operational' },
  { id:'astrakhan', name:'Astrakhan', country:'Russia', latitude:46.35, longitude:48.04, x:36, y:5, vessels:18, status:'Limited' },
  { id:'makhachkala', name:'Makhachkala', country:'Russia', latitude:42.97, longitude:47.50, x:29, y:35, vessels:15, status:'Operational' },
  { id:'anzali', name:'Anzali', country:'Iran', latitude:37.47, longitude:49.47, x:39, y:94, vessels:8, status:'Operational' },
  { id:'amirabad', name:'Amirabad', country:'Iran', latitude:36.85, longitude:53.37, x:63, y:96, vessels:10, status:'Busy' },
]

export const voyages: Voyage[] = [
  { id:'v-1', from:'Baku', to:'Aktau', departed:'10 Aug, 08:00', arrived:'—', distance:387, status:'In progress' },
  { id:'v-2', from:'Aktau', to:'Baku', departed:'06 Aug, 07:42', arrived:'06 Aug, 19:18', distance:391, status:'Completed' },
  { id:'v-3', from:'Baku', to:'Aktau', departed:'02 Aug, 09:15', arrived:'02 Aug, 20:46', distance:387, status:'Completed' },
  { id:'v-4', from:'Aktau', to:'Turkmenbashi', departed:'29 Jul, 05:30', arrived:'29 Jul, 15:12', distance:294, status:'Completed' },
  { id:'v-5', from:'Turkmenbashi', to:'Baku', departed:'25 Jul, 06:10', arrived:'25 Jul, 17:44', distance:306, status:'Completed' },
  { id:'v-6', from:'Alat', to:'Kuryk', departed:'21 Jul, 08:35', arrived:'22 Jul, 11:08', distance:412, status:'Completed' },
  { id:'v-7', from:'Aktau', to:'Astrakhan', departed:'17 Jul, 04:20', arrived:'18 Jul, 14:42', distance:534, status:'Completed' },
  { id:'v-8', from:'Makhachkala', to:'Baku', departed:'13 Jul, 10:05', arrived:'13 Jul, 19:56', distance:342, status:'Completed' },
  { id:'v-9', from:'Baku', to:'Turkmenbashi', departed:'09 Jul, 07:50', arrived:'09 Jul, 18:32', distance:301, status:'Completed' },
  { id:'v-10', from:'Anzali', to:'Baku', departed:'05 Jul, 05:15', arrived:'05 Jul, 15:03', distance:287, status:'Completed' },
  { id:'v-11', from:'Amirabad', to:'Turkmenbashi', departed:'01 Jul, 11:40', arrived:'02 Jul, 06:24', distance:463, status:'Completed' },
  { id:'v-12', from:'Kuryk', to:'Alat', departed:'27 Jun, 03:25', arrived:'28 Jun, 08:16', distance:417, status:'Completed' },
  { id:'v-13', from:'Astrakhan', to:'Aktau', departed:'22 Jun, 09:00', arrived:'24 Jun, 01:38', distance:542, status:'Completed' },
  { id:'v-14', from:'Baku', to:'Anzali', departed:'18 Jun, 12:30', arrived:'18 Jun, 22:14', distance:284, status:'Completed' },
]

export const events: MaritimeEvent[] = [
  { id:'e-1', type:'Route deviation', vessel:'KHAZAR WAVE', location:'Central Caspian', time:'Today, 14:32', severity:'Medium' },
  { id:'e-2', type:'Port call', vessel:'TURKMEN BREEZE', location:'Turkmenbashi', time:'Today, 13:48', severity:'Info' },
  { id:'e-3', type:'AIS gap', vessel:'ANZALI TRADER', location:'Southern Caspian', time:'Today, 11:14', severity:'Low' },
  { id:'e-4', type:'Weather', vessel:'—', location:'Northern Caspian', time:'Today, 09:05', severity:'Info' },
  { id:'e-5', type:'AIS gap', vessel:'TURAN', location:'Central Caspian', time:'Today, 16:42', severity:'Medium' },
  { id:'e-6', type:'Route deviation', vessel:'BAKU EXPRESS', location:'West-central Caspian', time:'Today, 15:55', severity:'Medium' },
  { id:'e-7', type:'Port call', vessel:'KURYK FERRY', location:'Kuryk anchorage', time:'Today, 15:31', severity:'Info' },
  { id:'e-8', type:'Weather', vessel:'VOLGA PEARL', location:'Northern Caspian', time:'Today, 14:20', severity:'Info' },
  { id:'e-9', type:'Route deviation', vessel:'CASPIAN WIND', location:'Eastern Caspian', time:'Today, 13:54', severity:'Medium' },
  { id:'e-10', type:'Port call', vessel:'MAKHACHKALA STAR', location:'Makhachkala', time:'Today, 12:48', severity:'Info' },
  { id:'e-11', type:'AIS gap', vessel:'DERBENT VOYAGER', location:'Western Caspian', time:'Today, 10:36', severity:'Low' },
  { id:'e-12', type:'Port call', vessel:'PORT BAKU', location:'Alat roads', time:'Today, 09:58', severity:'Info' },
  { id:'e-13', type:'Weather', vessel:'AMIRABAD CARGO', location:'Southern Caspian', time:'Today, 08:44', severity:'Info' },
  { id:'e-14', type:'Route deviation', vessel:'CASPIAN HORIZON', location:'Central Caspian', time:'Today, 07:26', severity:'Low' },
]

export const caspianStarTrack: TrackPoint[] = [
  { id:'tp-01', time:'08:00', label:'10 Aug, 08:00', latitude:40.37, longitude:49.89, x:35, y:60, speed:0, course:47, kind:'departure' },
  { id:'tp-02', time:'08:35', label:'10 Aug, 08:35', latitude:40.53, longitude:49.96, x:38, y:56, speed:8.4, course:28 },
  { id:'tp-03', time:'09:20', label:'10 Aug, 09:20', latitude:40.76, longitude:50.03, x:41, y:52, speed:11.2, course:20 },
  { id:'tp-04', time:'10:15', label:'10 Aug, 10:15', latitude:41.04, longitude:50.13, x:45, y:48, speed:11.7, course:24 },
  { id:'tp-05', time:'11:10', label:'10 Aug, 11:10', latitude:41.31, longitude:50.25, x:49, y:44, speed:11.8, course:27 },
  { id:'tp-06', time:'12:10', label:'10 Aug, 12:10', latitude:41.51, longitude:50.31, x:52, y:41, speed:.7, course:31, kind:'stop' },
  { id:'tp-07', time:'12:24', label:'10 Aug, 12:24', latitude:41.52, longitude:50.32, x:53, y:40, speed:.5, course:31, kind:'stop' },
  { id:'tp-08', time:'13:20', label:'10 Aug, 13:20', latitude:41.74, longitude:50.44, x:56, y:37, speed:11.6, course:36, kind:'course' },
  { id:'tp-09', time:'14:10', label:'10 Aug, 14:10', latitude:41.89, longitude:50.52, x:58, y:35, speed:11.8, course:39, kind:'gap' },
  { id:'tp-10', time:'17:25', label:'10 Aug, 17:25', latitude:42.04, longitude:50.61, x:60, y:33, speed:12, course:42, kind:'restored' },
  { id:'tp-11', time:'18:05', label:'10 Aug, 18:05', latitude:42.18, longitude:50.68, x:62, y:31, speed:12.2, course:45 },
  { id:'tp-12', time:'18:42', label:'10 Aug, 18:42', latitude:42.31, longitude:50.74, x:64, y:29, speed:12.4, course:47 },
]

export const trackingEvents: TrackingEvent[] = [
  { id:'te-01', time:'08:00', title:'Выход из порта Baku', description:'Начало рейса CI-240810', kind:'departure' },
  { id:'te-02', time:'12:10', title:'Остановка движения', description:'Продолжительность 14 минут', kind:'stop' },
  { id:'te-03', time:'13:20', title:'Изменение курса', description:'Курс изменён с 28° на 36°', kind:'course' },
  { id:'te-04', time:'14:10', title:'Последняя позиция', description:'Данные временно не поступали', kind:'gap' },
  { id:'te-05', time:'17:25', title:'Новая позиция получена', description:'Приём данных восстановлен', kind:'restored' },
]

export const caspianStarBehavior = {
  confidence: 94,
  confidenceLevel: 'HIGH CONFIDENCE',
  voyagesAnalyzed: 143,
  observationMonths: 18,
  distanceTracked: 31420,
  sailingHours: 3810,
  portHours: 1280,
  aisGaps: 8,
  mainRoute: 'Baku → Aktau',
  routes: [
    { id:'baku-aktau', from:'Baku', to:'Aktau', voyages:82, share:57, distance:'380–405 km', duration:'27–31 h', speed:'11.2–13.1 kn', stops:'0–1', departure:'06:00–11:00', arrival:'10:00–17:00', color:'#08796e' },
    { id:'aktau-baku', from:'Aktau', to:'Baku', voyages:41, share:29, distance:'382–408 km', duration:'28–32 h', speed:'10.9–12.8 kn', stops:'0–1', departure:'07:00–12:00', arrival:'11:00–18:00', color:'#5b928a' },
    { id:'aktau-turkmenbashi', from:'Aktau', to:'Turkmenbashi', voyages:14, share:10, distance:'285–310 km', duration:'24–29 h', speed:'9.1–11.3 kn', stops:'0–2', departure:'05:00–10:00', arrival:'09:00–16:00', color:'#99b9b3' },
    { id:'other', from:'Other', to:'Other', voyages:6, share:4, distance:'—', duration:'—', speed:'—', stops:'—', departure:'—', arrival:'—', color:'#d9e1de' },
  ],
  speed: { average:12.1, median:12.0, p95:13.8, min:11.2, max:13.1, samples:48220, distribution:[1,2,3,5,9,18,34,57,81,96,82,54,27,11,4] },
  duration: { average:'29h 12m', median:'28h 47m', typical:'27–31 h', fastest:'25h 51m', longest:'36h 14m', samples:82 },
  ports: [
    { name:'Aktau', visits:61, share:43, stay:'4–11 h', median:'6h 48m', usual:true },
    { name:'Baku', visits:57, share:40, stay:'4.5–12 h', median:'7h 12m', usual:true },
    { name:'Turkmenbashi', visits:18, share:13, stay:'5–14 h', median:'8h 24m', usual:true },
    { name:'Kuryk', visits:5, share:3, stay:'3–9 h', median:'5h 54m', usual:false },
    { name:'Other', visits:2, share:1, stay:'2–7 h', median:'4h 06m', usual:false },
  ],
  stops: [
    { id:'sa-1', x:53, y:40, count:12, duration:'19 min', radius:34 },
    { id:'sa-2', x:44, y:51, count:7, duration:'27 min', radius:26 },
    { id:'sa-3', x:59, y:35, count:5, duration:'31 min', radius:22 },
  ],
  draught: [
    { voyage:'140', route:'Aktau → Baku', start:4.7, end:4.8 },
    { voyage:'141', route:'Baku → Aktau', start:5.2, end:4.1 },
    { voyage:'142', route:'Aktau → Turkmenbashi', start:4.3, end:4.4 },
    { voyage:'143', route:'Baku → Aktau', start:4.8, end:4.8 },
  ],
  departurePattern:[7,58,29,6],
  weekdays:[18,24,22,25,19,9,5],
  comparison:[
    { parameter:'Скорость', typical:'11.2–13.1 kn', current:'12.4 kn' },
    { parameter:'Дистанция', typical:'380–405 km', current:'258 km пока' },
    { parameter:'Длительность', typical:'27–31 h', current:'16 h пока' },
    { parameter:'Остановки', typical:'0–1', current:'0' },
    { parameter:'Маршрут', typical:'Baku → Aktau', current:'Baku → Aktau' },
    { parameter:'Осадка', typical:'4.5–5.1 m', current:'4.8 m' },
  ],
}

export const detectedEvents: DetectionEvent[] = [
  { id:'EV-2801', type:'route_deviation', vesselId:'caspian-star', vesselName:'CASPIAN STAR', voyageId:'voy-001', groupId:'EG-441', startedAt:'10 Aug 2026, 13:20', time:'13:20', x:57, y:40, latitude:41.34, longitude:50.75, severity:'medium', confidence:94, status:'active', title:'Отклонение от маршрута', summary:'38 км от исторического коридора', explanation:'Судно вышло за исторический коридор маршрута Baku → Aktau. Событие отражает отличие от собственного baseline и требует просмотра в контексте рейса.', factors:['Исторический коридор: ±8 км','Текущее отклонение: 38 км','Исторический percentile: 99.4%','Проанализировано 82 рейса'], metrics:[{label:'Текущее отклонение',value:'38 km',baseline:'Обычно 0–8 km'},{label:'Продолжительность',value:'47 min'},{label:'Историческая выборка',value:'82 voyages'}] },
  { id:'EV-2802', type:'ais_gap', vesselId:'caspian-star', vesselName:'CASPIAN STAR', voyageId:'voy-001', groupId:'EG-441', startedAt:'10 Aug 2026, 14:10', endedAt:'10 Aug 2026, 17:25', time:'14:10', x:59, y:35, latitude:41.89, longitude:50.52, severity:'high', confidence:98, status:'resolved', title:'Разрыв AIS', summary:'3 ч 15 мин без данных', explanation:'Позиционные сообщения отсутствовали 3 часа 15 минут в зоне с высоким качеством AIS-покрытия. Само отсутствие сигнала не означает намеренного отключения.', factors:['Последняя позиция: 14:10','Сигнал восстановлен: 17:25','Качество покрытия: HIGH','Возможный радиус движения: 72 км'], metrics:[{label:'Продолжительность',value:'3h 15m',baseline:'Класс LONG'},{label:'Покрытие района',value:'HIGH'},{label:'Возможная область',value:'72 km radius'}] },
  { id:'EV-2803', type:'vessel_encounter', vesselId:'caspian-star', vesselName:'CASPIAN STAR', relatedVessel:'TURAN', voyageId:'voy-001', groupId:'EG-441', startedAt:'10 Aug 2026, 17:28', endedAt:'10 Aug 2026, 20:15', time:'17:28', x:61, y:33, latitude:42.04, longitude:50.61, severity:'medium', confidence:93, status:'resolved', title:'Встреча судов', summary:'CASPIAN STAR + TURAN · 174 м', explanation:'Два судна продолжительное время находились рядом при низкой скорости в открытом море. Событие описывает наблюдаемый факт совместного присутствия.', factors:['Минимальная дистанция: 174 м','Продолжительность: 2 ч 47 мин','Скорость: 0.3 / 0.4 kn','Предыдущие наблюдения: 3'], metrics:[{label:'Минимальная дистанция',value:'174 m'},{label:'Продолжительность',value:'2h 47m'},{label:'Средняя скорость',value:'0.3 / 0.4 kn'}] },
  { id:'EV-2804', type:'draught_change', vesselId:'caspian-star', vesselName:'CASPIAN STAR', voyageId:'voy-001', groupId:'EG-441', startedAt:'10 Aug 2026, 17:40', time:'17:40', x:62, y:32, latitude:42.05, longitude:50.62, severity:'low', confidence:96, status:'resolved', title:'Изменение осадки', summary:'4.1 → 5.0 м · изменение +0.9 м', explanation:'После восстановления данных получено изменение заявленной осадки. Требуется проверить качество источника и контекст рейса.', factors:['До события: 4.1 м','После события: 5.0 м','Изменение: +0.9 м','Положение: вне порта'], metrics:[{label:'До',value:'4.1 m'},{label:'После',value:'5.0 m'},{label:'Изменение',value:'+0.9 m'}] },
  { id:'EV-2805', type:'unexpected_speed', vesselId:'volga-marine', vesselName:'VOLGA MARINE', voyageId:'voy-207', startedAt:'10 Aug 2026, 12:00', time:'12:00', x:36, y:22, latitude:43.10, longitude:48.95, severity:'medium', confidence:91, status:'active', title:'Нетипичная скорость', summary:'2.9 kn в открытом море · 42 мин', explanation:'Скорость судна сохранялась ниже его типичного диапазона для открытого моря более 30 минут.', factors:['Фаза рейса: OPEN SEA','Обычно: 6.5–8.5 kn','Текущая скорость: 2.9 kn','Продолжительность: 42 мин'], metrics:[{label:'Сейчас',value:'2.9 kn',baseline:'Обычно 6.5–8.5 kn'},{label:'Продолжительность',value:'42 min'}] },
  { id:'EV-2806', type:'unusual_stop', vesselId:'khazar-wave', vesselName:'KHAZAR WAVE', voyageId:'voy-184', startedAt:'10 Aug 2026, 11:20', time:'11:20', x:49, y:61, latitude:40.82, longitude:50.21, severity:'medium', confidence:90, status:'active', title:'Нетипичная остановка', summary:'74 мин в открытом море', explanation:'Судно почти неподвижно вне порта, якорной зоны и известных исторических зон остановок.', factors:['Скорость: 0.3 kn','Продолжительность: 74 мин','Контекст: OPEN SEA','Неизвестная зона остановки'], metrics:[{label:'Продолжительность',value:'74 min',baseline:'Обычно до 24 min'},{label:'Скорость',value:'0.3 kn'},{label:'Контекст',value:'Open sea'}] },
  { id:'EV-2807', type:'ais_gap', vesselId:'turan', vesselName:'TURAN', voyageId:'voy-211', startedAt:'10 Aug 2026, 16:42', endedAt:'10 Aug 2026, 17:31', time:'16:42', x:60, y:33, latitude:42.01, longitude:50.58, severity:'medium', confidence:86, status:'resolved', title:'Неполный интервал AIS', summary:'49 мин без позиционных сообщений', explanation:'Поток AIS прерывался в зоне среднего качества покрытия. Система фиксирует отсутствие данных, но не определяет его причину.', factors:['Продолжительность: 49 мин','Покрытие: MEDIUM','Сигнал восстановлен: 17:31'], metrics:[{label:'Продолжительность',value:'49 min',baseline:'Обычно до 18 min'},{label:'Покрытие',value:'MEDIUM'}] },
  { id:'EV-2808', type:'route_deviation', vesselId:'baku-express', vesselName:'BAKU EXPRESS', voyageId:'voy-221', startedAt:'10 Aug 2026, 15:55', time:'15:55', x:44, y:55, latitude:40.92, longitude:50.18, severity:'medium', confidence:91, status:'active', title:'Отклонение от коридора', summary:'27 км от типичного маршрута Alat → Kuryk', explanation:'Текущая позиция находится вне исторического коридора судна. Возможны погодные или операционные причины, которые требуют проверки.', factors:['Отклонение: 27 км','Исторических рейсов: 38','Ветер: 16 kn'], metrics:[{label:'Отклонение',value:'27 km',baseline:'Обычно 0–9 km'},{label:'Уверенность',value:'91%'}] },
  { id:'EV-2809', type:'unexpected_speed', vesselId:'caspian-wind', vesselName:'CASPIAN WIND', voyageId:'voy-174', startedAt:'10 Aug 2026, 14:18', time:'14:18', x:69, y:62, latitude:41.35, longitude:52.18, severity:'low', confidence:82, status:'active', title:'Скорость ниже профиля', summary:'6.4 kn при обычных 8.1–10.7 kn', explanation:'Скорость ниже индивидуального диапазона, однако погодная поправка частично объясняет наблюдение.', factors:['Текущая скорость: 6.4 kn','Волна: 1.8 m','Встречный ветер: 19 kn'], metrics:[{label:'Скорость',value:'6.4 kn',baseline:'Обычно 8.1–10.7 kn'},{label:'Погода',value:'19 kn headwind'}] },
  { id:'EV-2810', type:'unusual_stop', vesselId:'derbent-voyager', vesselName:'DERBENT VOYAGER', voyageId:'voy-232', startedAt:'10 Aug 2026, 13:06', endedAt:'10 Aug 2026, 13:43', time:'13:06', x:27, y:46, latitude:42.12, longitude:48.12, severity:'low', confidence:79, status:'resolved', title:'Остановка вне порта', summary:'37 мин при скорости менее 0.5 kn', explanation:'Короткая остановка произошла вне известной якорной зоны. Продолжительность близка к порогу и имеет умеренную уверенность.', factors:['Продолжительность: 37 мин','Минимальная скорость: 0.2 kn','До берега: 31 км'], metrics:[{label:'Продолжительность',value:'37 min',baseline:'Порог 30 min'},{label:'Скорость',value:'0.2 kn'}] },
  { id:'EV-2811', type:'draught_change', vesselId:'aral-pioneer', vesselName:'ARAL PIONEER', voyageId:'voy-238', startedAt:'10 Aug 2026, 12:52', time:'12:52', x:47, y:14, latitude:43.76, longitude:50.02, severity:'low', confidence:88, status:'reviewed', title:'Обновление осадки', summary:'6.1 → 6.4 м после выхода из речной зоны', explanation:'AIS-сообщение содержит новое значение осадки. Изменение может быть связано с качеством ручного ввода и отмечено для проверки источника.', factors:['Предыдущее значение: 6.1 м','Новое значение: 6.4 м','Источник: AIS static data'], metrics:[{label:'До',value:'6.1 m'},{label:'После',value:'6.4 m'},{label:'Изменение',value:'+0.3 m'}] },
  { id:'EV-2812', type:'vessel_encounter', vesselId:'absheron-spirit', vesselName:'ABSHERON SPIRIT', relatedVessel:'PORT BAKU', voyageId:'voy-245', startedAt:'10 Aug 2026, 12:18', endedAt:'10 Aug 2026, 12:46', time:'12:18', x:48, y:69, latitude:40.04, longitude:50.02, severity:'low', confidence:89, status:'resolved', title:'Сближение судов', summary:'420 м · 28 мин в районе подхода к Alat', explanation:'Два судна находились рядом на малой скорости в портовом подходном коридоре. Контекст района снижает значимость события.', factors:['Минимальная дистанция: 420 м','Продолжительность: 28 мин','Контекст: PORT APPROACH'], metrics:[{label:'Дистанция',value:'420 m'},{label:'Продолжительность',value:'28 min'},{label:'Контекст',value:'Port approach'}] },
  { id:'EV-2813', type:'fuel_anomaly', vesselId:'caspian-horizon', vesselName:'CASPIAN HORIZON', voyageId:'voy-251', startedAt:'10 Aug 2026, 11:44', time:'11:44', x:63, y:55, latitude:41.06, longitude:51.44, severity:'medium', confidence:84, status:'active', title:'Отклонение расхода топлива', summary:'+21% к погодному прогнозу модели', explanation:'Заявленный расход выше диапазона vessel-specific модели после учета ветра, волны и режима движения. Значение требует сверки с отчетом оператора.', factors:['Ожидалось: 31–36 t','Заявлено: 43.6 t','Погодная поправка: +7%'], metrics:[{label:'Ожидалось',value:'31–36 t'},{label:'Заявлено',value:'43.6 t'},{label:'Отклонение',value:'+21%'}] },
  { id:'EV-2814', type:'route_deviation', vesselId:'volga-pearl', vesselName:'VOLGA PEARL', voyageId:'voy-259', startedAt:'10 Aug 2026, 10:38', time:'10:38', x:34, y:10, latitude:44.38, longitude:48.74, severity:'low', confidence:77, status:'active', title:'Изменение речного подхода', summary:'12 км от сезонного коридора', explanation:'Маршрут отличается от сезонного baseline северного участка. Низкая полнота AIS и навигационные ограничения учтены в уверенности.', factors:['Отклонение: 12 км','AIS coverage: 74%','Сезонный baseline: июнь–август'], metrics:[{label:'Отклонение',value:'12 km',baseline:'Обычно 0–7 km'},{label:'Покрытие',value:'74%'}] },
]

export const demoEventGroup = {
  id:'EG-441', vessel:'CASPIAN STAR', voyage:'Voyage #143', startedAt:'13:20', endedAt:'17:40',
  eventIds:['EV-2801','EV-2802','EV-2803','EV-2804'],
  explanation:'Четыре события связаны одним судном, рейсом и временным контекстом. Группа предназначена для совместного просмотра фактов.',
}

const recentCaspianVoyages: RiskAssessment['recentVoyages'] = [
  { id:'V-143', route:'Baku → Aktau', date:'10 авг 2026', score:91, level:'CRITICAL' },
  { id:'V-142', route:'Aktau → Turkmenbashi', date:'06 авг 2026', score:18, level:'LOW' },
  { id:'V-141', route:'Baku → Aktau', date:'02 авг 2026', score:32, level:'MODERATE' },
  { id:'V-140', route:'Aktau → Baku', date:'29 июл 2026', score:11, level:'LOW' },
  { id:'V-139', route:'Baku → Aktau', date:'24 июл 2026', score:21, level:'LOW' },
  { id:'V-138', route:'Aktau → Baku', date:'19 июл 2026', score:14, level:'LOW' },
  { id:'V-137', route:'Baku → Aktau', date:'14 июл 2026', score:27, level:'MODERATE' },
  { id:'V-136', route:'Aktau → Baku', date:'09 июл 2026', score:9, level:'LOW' },
  { id:'V-135', route:'Baku → Aktau', date:'04 июл 2026', score:16, level:'LOW' },
  { id:'V-134', route:'Aktau → Baku', date:'29 июн 2026', score:13, level:'LOW' },
]

export const riskAssessments: RiskAssessment[] = [
  {
    vesselId:'caspian-star', vesselName:'CASPIAN STAR', imo:'9384721', voyageId:'V-143', route:'Baku → Aktau',
    score:91, level:'CRITICAL', previousScore:84, delta:7, deltaWindow:'6 мин', updatedAt:'10 авг, 17:46', modelVersion:'CI-RISK-2.0', voyageScore:91, vesselScore:25, correlationScore:15, rawFactorScore:102, baseEventScore:84, advancedEffectiveScore:7, x:61, y:33,
    scenario:{ code:'POTENTIAL_OFFSHORE_TRANSFER_PATTERN', label:'PATTERN REQUIRES REVIEW', confidence:88, explanation:'Последовательность событий похожа на ранее описанный операционный паттерн. Это основание для проверки, а не утверждение о нарушении.' },
    factors:[
      { id:'RF-901', type:'ais_gap', title:'Продолжительный разрыв AIS', baseScore:10, adjustedScore:22, confidence:98, sourceEventId:'EV-2802', explanation:'Разрыв продолжался 3 ч 15 мин в зоне с высоким качеством покрытия; для судна такие разрывы редки.', evidence:['3 ч 15 мин без данных','AIS coverage: HIGH','8 разрывов за 18 месяцев'], createdAt:'14:10', lifecycle:'RECENT', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-904', type:'draught_change', title:'Изменение осадки после разрыва', baseScore:5, adjustedScore:18, confidence:96, sourceEventId:'EV-2804', explanation:'Заявленная осадка изменилась на +0.9 м вне порта после восстановления AIS и наблюдаемой встречи.', evidence:['4.1 → 5.0 м','Изменение: +0.9 м','Положение вне порта'], createdAt:'17:40', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-903', type:'vessel_encounter', title:'Продолжительная встреча судов', baseScore:7, adjustedScore:17, confidence:93, sourceEventId:'EV-2803', explanation:'Два судна находились на дистанции 174 м при низкой скорости почти три часа в открытом море.', evidence:['Минимум 174 м','2 ч 47 мин рядом','Скорость 0.3 / 0.4 kn'], createdAt:'17:28', lifecycle:'RECENT', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-900', type:'route_deviation', title:'Выход из исторического коридора', baseScore:6, adjustedScore:12, confidence:94, sourceEventId:'EV-2801', explanation:'Отклонение 38 км существенно превышает собственный исторический коридор судна ±8 км.', evidence:['Отклонение: 38 км','Обычно: 0–8 км','82 сопоставимых рейса'], createdAt:'13:20', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-950', type:'cargo_draught_mismatch', title:'Груз не объясняет наблюдаемую осадку', baseScore:7, adjustedScore:13, effectiveScore:3, confidence:87, explanation:'Vessel-specific модель ожидает изменение +1.05–1.30 м для заявленных 5 000 т стали; в доступных данных наблюдается +0.30 м.', evidence:['Ожидалось: +1.05–1.30 м','Наблюдается: +0.30 м','63 грузовые операции'], createdAt:'17:42', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-951', type:'fuel_anomaly', title:'Расход топлива выше ожидаемого', baseScore:5, adjustedScore:9, effectiveScore:2, confidence:82, explanation:'После поправок на ветер, волны, течение, ожидание и маневрирование заявленные 61 т остаются выше диапазона 38–44 т.', evidence:['Ожидалось: 38–44 т','Заявлено: 61 т','Погода +4% · операции +6%'], createdAt:'17:43', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-952', type:'economic_anomaly', title:'Экономически нетипичное соотношение', baseScore:4, adjustedScore:6, effectiveScore:1, confidence:68, explanation:'Оценочная стоимость груза ниже расчётной стоимости рейса. Показатель служит только основанием для проверки исходных данных.', evidence:['Cargo value: $250k','Voyage cost: $320k','Ratio 0.78 · обычно 2.4–4.8'], createdAt:'17:44', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-953', type:'unusual_connection', title:'Устойчивая историческая связь с TURAN', baseScore:3, adjustedScore:5, effectiveScore:1, confidence:91, explanation:'За шесть месяцев агрегировано 14 встреч, из них 11 в открытом море. Связь отражает повторяемость совместного присутствия, а не перенос риска.', evidence:['14 встреч','11 в открытом море','18 ч 42 мин суммарно'], createdAt:'17:45', lifecycle:'RECENT', reviewStatus:'NEEDS_MORE_DATA' },
    ],
    history:[
      { time:'08:00', score:12, level:'LOW', reason:'Начало рейса' },
      { time:'13:20', score:27, level:'MODERATE', reason:'Отклонение от маршрута' },
      { time:'14:10', score:35, level:'MODERATE', reason:'Зафиксирован разрыв AIS' },
      { time:'17:25', score:54, level:'HIGH', reason:'AIS восстановлен после 3 ч 15 мин' },
      { time:'17:30', score:68, level:'HIGH', reason:'Подтверждена встреча судов' },
      { time:'17:40', score:84, level:'CRITICAL', reason:'Изменение осадки и корреляция факторов' },
      { time:'17:46', score:91, level:'CRITICAL', reason:'Груз, топливо, экономика и историческая связь' },
    ],
    recentVoyages:recentCaspianVoyages,
  },
  {
    vesselId:'turan', vesselName:'TURAN', imo:'9217748', voyageId:'V-088', route:'Aktau → Baku',
    score:71, level:'HIGH', previousScore:59, delta:12, deltaWindow:'2 ч', updatedAt:'10 авг, 17:36', modelVersion:'CI-RISK-1.0', voyageScore:71, vesselScore:37, correlationScore:9, x:58, y:39,
    factors:[
      { id:'RF-910', type:'vessel_encounter', title:'Повторная встреча с CASPIAN STAR', baseScore:9, adjustedScore:24, confidence:92, sourceEventId:'EV-2803', explanation:'Продолжительное сближение в открытом море при низкой скорости.', evidence:['174 м','2 ч 47 мин','3 прошлые встречи'], createdAt:'17:28', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-911', type:'ais_gap', title:'Неполная последовательность позиций', baseScore:8, adjustedScore:18, confidence:86, explanation:'В данных есть интервалы, ограничивающие восстановление полного трека.', evidence:['2 неполных интервала','Coverage: MEDIUM'], createdAt:'16:42', lifecycle:'RECENT', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-912', type:'route_deviation', title:'Нетипичная зона движения', baseScore:7, adjustedScore:20, confidence:89, explanation:'Точка встречи лежит вне обычного коридора этого судна.', evidence:['31 км от коридора','64 исторических рейса'], createdAt:'15:50', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
    ],
    history:[{time:'12:00',score:33,level:'MODERATE',reason:'Начало наблюдения'},{time:'16:42',score:59,level:'HIGH',reason:'Неполная последовательность позиций'},{time:'17:36',score:71,level:'HIGH',reason:'Связанные факторы встречи'}], recentVoyages:[],
  },
  {
    vesselId:'baku-express', vesselName:'BAKU EXPRESS', imo:'9451180', voyageId:'V-221', route:'Baku → Kuryk',
    score:63, level:'HIGH', previousScore:63, delta:0, deltaWindow:'3 ч', updatedAt:'10 авг, 17:22', modelVersion:'CI-RISK-1.0', voyageScore:63, vesselScore:29, correlationScore:7, x:42, y:55,
    factors:[
      { id:'RF-920', type:'route_deviation', title:'Изменение маршрута', baseScore:8, adjustedScore:22, confidence:91, explanation:'Движение вне устойчивого исторического коридора.', evidence:['27 км от коридора'], createdAt:'13:55', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-921', type:'unusual_stop', title:'Нетипичная остановка', baseScore:7, adjustedScore:16, confidence:88, explanation:'Остановка вне порта и известных зон ожидания.', evidence:['86 мин','Open sea'], createdAt:'14:40', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-922', type:'unexpected_speed', title:'Нетипичная скорость', baseScore:6, adjustedScore:18, confidence:84, explanation:'Скорость ниже диапазона для текущей фазы рейса.', evidence:['1.1 kn','Обычно 8–11 kn'], createdAt:'15:05', lifecycle:'RECENT', reviewStatus:'NEEDS_MORE_DATA' },
    ],
    history:[{time:'13:55',score:22,level:'LOW',reason:'Изменение маршрута'},{time:'14:40',score:45,level:'MODERATE',reason:'Нетипичная остановка'},{time:'15:05',score:63,level:'HIGH',reason:'Корреляция скорости и остановки'}], recentVoyages:[],
  },
  {
    vesselId:'caspian-wind', vesselName:'CASPIAN WIND', imo:'9347014', voyageId:'V-174', route:'Turkmenbashi → Aktau',
    score:51, level:'HIGH', previousScore:46, delta:5, deltaWindow:'1 ч', updatedAt:'10 авг, 17:18', modelVersion:'CI-RISK-1.0', voyageScore:51, vesselScore:18, correlationScore:5, x:69, y:62,
    factors:[
      { id:'RF-930', type:'ais_gap', title:'Разрыв AIS', baseScore:9, adjustedScore:19, confidence:89, explanation:'Отсутствие сообщений превысило типичный интервал.', evidence:['1 ч 42 мин','Coverage: HIGH'], createdAt:'15:11', lifecycle:'RECENT', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-931', type:'unusual_stop', title:'Остановка вне обычной зоны', baseScore:8, adjustedScore:15, confidence:85, explanation:'Положение не совпало с портом или исторической зоной.', evidence:['52 мин','0.2 kn'], createdAt:'16:02', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
      { id:'RF-932', type:'route_deviation', title:'Отклонение маршрута', baseScore:6, adjustedScore:12, confidence:82, explanation:'Наблюдаемая точка находится за границей коридора.', evidence:['19 км от коридора'], createdAt:'16:30', lifecycle:'ACTIVE', reviewStatus:'NEEDS_MORE_DATA' },
    ],
    history:[{time:'15:11',score:19,level:'LOW',reason:'Разрыв AIS'},{time:'16:02',score:39,level:'MODERATE',reason:'Остановка вне обычной зоны'},{time:'17:18',score:51,level:'HIGH',reason:'Связанные факторы'}], recentVoyages:[],
  },
]

export const voyageIntelligence: VoyageIntelligence = {
  id:'voy-001', displayId:'Voyage #143', vesselId:'caspian-star', vesselName:'CASPIAN STAR', imo:'9384721',
  route:{from:'Baku',to:'Aktau',distance:'390 km',deviation:'38 km'}, startedAt:'10 авг 2026 · 08:00', eta:'11 авг · 15:12',
  riskScore:91, riskLevel:'CRITICAL', significantFactors:7,
  summary:'Текущий рейс существенно отличается от исторического профиля судна. Маршрут, разрыв AIS и встреча в море дополнены несоответствиями в данных об осадке, топливе и экономике. Совокупность признаков требует проверки аналитиком и не является выводом о нарушении.',
  mainFactors:['Отклонение от маршрута на 38 км','Разрыв AIS 3 ч 15 мин','Встреча с TURAN в открытом море','Cargo / draught mismatch','Расход топлива выше ожидаемого'],
  cargo:{
    type:{label:'Тип груза',value:'Steel',status:'REPORTED',source:'Baku port declaration',sourceTimestamp:'10 авг · 07:42',confidence:'HIGH'},
    mass:{label:'Заявленная масса',value:'5 000 t',status:'REPORTED',source:'Baku port declaration',sourceTimestamp:'10 авг · 07:42',confidence:'HIGH'},
    value:{label:'Заявленная стоимость',value:'$250 000',status:'REPORTED',source:'Baku port declaration',sourceTimestamp:'10 авг · 07:42',confidence:'HIGH'},
    shipper:{label:'Отправитель',value:'Baku Metals Export JSC',status:'REPORTED',source:'Baku port declaration',sourceTimestamp:'10 авг · 07:42',confidence:'HIGH'},
    consignee:{label:'Получатель',value:'Aktau Industrial Supply LLP',status:'REPORTED',source:'Baku port declaration',sourceTimestamp:'10 авг · 07:42',confidence:'HIGH'},
    documentReference:'PORT-BAK-2026-0810-143',origin:'Baku',destination:'Aktau',
    history:[{label:'Steel',share:41},{label:'Grain',share:27},{label:'Equipment',share:18},{label:'Oil products',share:9},{label:'Other',share:5}],
  },
  draught:{
    departure:{label:'Осадка при выходе',value:'4.2 m',status:'REPORTED',source:'AIS draught report',sourceTimestamp:'10 авг · 08:00',confidence:'HIGH'},
    observed:{label:'Наблюдаемая осадка',value:'4.5 m',status:'REPORTED',source:'AIS draught report',sourceTimestamp:'10 авг · 17:40',confidence:'HIGH'},
    expectedRange:{label:'Ожидаемая осадка',value:'5.25–5.50 m',status:'ESTIMATED',source:'Vessel-specific draught model',sourceTimestamp:'10 авг · 17:42',confidence:'HIGH'},
    expectedChange:'+1.05–1.30 m',observedChange:'+0.30 m',modelConfidence:87,operationsAnalyzed:63,vesselSpecificRange:'+0.21–0.26 m / 1 000 t',
  },
  fuel:{
    expected:{label:'Ожидаемый расход',value:'38–44 t',status:'ESTIMATED',source:'CI vessel-specific fuel model',sourceTimestamp:'10 авг · 17:44',confidence:'HIGH'},
    reported:{label:'Заявленный расход',value:'61 t',status:'REPORTED',source:'Operator voyage report',sourceTimestamp:'10 авг · 17:32',confidence:'MEDIUM'},
    weatherCorrection:'+4% · ветер 18 kn, волна 1.4 m, течение 0.4 kn',operationalCorrection:'+6% · ожидание 2.2 h, маневрирование 0.8 h',finalDeviation:'+38.6% от верхней границы',engine:'MAN 8L32/40',typicalSpeed:'11–13 kn',
  },
  economics:{
    cargoValue:{label:'Стоимость груза',value:'$250 000',status:'ESTIMATED',source:'Market-based cargo value estimate',sourceTimestamp:'10 авг · 17:43',confidence:'LOW'},
    voyageCost:{label:'Стоимость рейса',value:'$320 000',status:'ESTIMATED',source:'Voyage cost model',sourceTimestamp:'10 авг · 17:45',confidence:'MEDIUM'},
    ratio:.78,typicalRatio:'2.4–4.8',
    costBreakdown:[{label:'Fuel',value:82000},{label:'Port fees',value:54000},{label:'Crew',value:38000},{label:'Handling',value:91000},{label:'Operations',value:55000}],
  },
  encounter:{vesselId:'turan',vesselName:'TURAN',duration:'2 ч 47 мин',minimumDistance:'174 m',previousEncounters:14},
  timeline:[
    {time:'07:42',title:'Груз заявлен портовой декларацией',description:'5 000 t steel · PORT-BAK-2026-0810-143',kind:'cargo',status:'REPORTED'},
    {time:'08:00',title:'Выход из Baku',description:'Начало Voyage #143 · осадка 4.2 m',kind:'voyage',status:'VERIFIED'},
    {time:'13:20',title:'Отклонение от исторического маршрута',description:'38 км при обычном коридоре 0–8 км',kind:'route'},
    {time:'14:10',title:'Начало разрыва AIS',description:'Позиционные данные отсутствуют 3 ч 15 мин',kind:'ais'},
    {time:'17:25',title:'AIS восстановлен',description:'Новая позиция получена вне исторического коридора',kind:'ais'},
    {time:'17:28',title:'Встреча с TURAN',description:'174 m · низкая скорость · открытое море',kind:'encounter'},
    {time:'17:42',title:'Cargo / draught mismatch',description:'Ожидаемое изменение +1.05–1.30 m, наблюдаемое +0.30 m',kind:'draught',status:'ESTIMATED'},
    {time:'17:43',title:'Fuel anomaly',description:'38–44 t после поправок против 61 t в отчёте',kind:'fuel',status:'ESTIMATED'},
    {time:'17:44',title:'Economic anomaly',description:'Ratio 0.78 при историческом диапазоне 2.4–4.8',kind:'economics',status:'ESTIMATED'},
    {time:'17:46',title:'Risk обновлён до 91',description:'Advanced context дал эффективный вклад +7 после confidence и deduplication',kind:'voyage'},
  ],
}

export const investigationNetwork: InvestigationNetwork = {
  nodes:[
    {id:'caspian-star',label:'CASPIAN STAR',subtitle:'Cargo vessel · risk 91',type:'VESSEL',x:50,y:48,risk:91,details:[{label:'IMO',value:'9384721'},{label:'Flag',value:'Kazakhstan'},{label:'Current voyage',value:'Baku → Aktau'},{label:'Operator',value:'Caspian Marine Co.'}]},
    {id:'turan',label:'TURAN',subtitle:'Cargo vessel · 14 encounters',type:'VESSEL',x:20,y:48,risk:71,details:[{label:'IMO',value:'9217748'},{label:'Flag',value:'Azerbaijan'},{label:'Encounters',value:'14 / 6 months'},{label:'Open sea',value:'11'}]},
    {id:'company-a',label:'Caspian Marine Co.',subtitle:'Reported owner / operator',type:'COMPANY',x:50,y:15,details:[{label:'Role',value:'Owner / operator'},{label:'Country',value:'Kazakhstan'},{label:'Fleet in API profile',value:'2 vessels'},{label:'Voyages',value:'126'},{label:'Source',value:'Demo corporate registry extract · REPORTED'},{label:'Confidence',value:'79%'}]},
    {id:'owner-a',label:'Caspian Marine Co.',subtitle:'Reported owner party',type:'OWNER',x:25,y:9,details:[{label:'Relationship',value:'Reported owner of CASPIAN STAR'},{label:'Source',value:'Demo corporate registry extract'},{label:'Confidence',value:'79% · MEDIUM'},{label:'Status',value:'REPORTED · requires registry verification'}]},
    {id:'company-b',label:'Turan Maritime Services',subtitle:'Reported TURAN operator',type:'COMPANY',x:12,y:72,details:[{label:'Role',value:'Operator'},{label:'Country',value:'Azerbaijan'},{label:'Fleet in API profile',value:'1 vessel'},{label:'Voyages',value:'74'},{label:'Source',value:'Demo corporate registry extract · REPORTED'},{label:'Confidence',value:'76%'}]},
    {id:'baku',label:'BAKU',subtitle:'Departure port',type:'PORT',x:75,y:16,details:[{label:'Relationship',value:'Visited / departed'},{label:'Calls, 18 months',value:'57'},{label:'Last call',value:'10 Aug 2026'},{label:'Country',value:'Azerbaijan'}]},
    {id:'aktau',label:'AKTAU',subtitle:'Destination port',type:'PORT',x:86,y:48,details:[{label:'Relationship',value:'Destination'},{label:'Calls, 18 months',value:'61'},{label:'ETA',value:'11 Aug · 15:12'},{label:'Country',value:'Kazakhstan'}]},
    {id:'cargo-steel',label:'STEEL · 5 000 t',subtitle:'Reported cargo',type:'CARGO',x:75,y:78,details:[{label:'Status',value:'REPORTED'},{label:'Origin',value:'Baku'},{label:'Destination',value:'Aktau'},{label:'Document',value:'PORT-BAK-2026-0810-143'}]},
    {id:'voy-001',label:'VOYAGE #143',subtitle:'Baku → Aktau',type:'VOYAGE',x:48,y:84,details:[{label:'Started',value:'10 Aug · 08:00'},{label:'Distance',value:'390 km'},{label:'Risk',value:'91 / 100'},{label:'Status',value:'In progress'}]},
    {id:'caspian-wind',label:'CASPIAN WIND',subtitle:'Oil tanker · 8 encounters',type:'VESSEL',x:13,y:28,risk:51,details:[{label:'IMO',value:'9347011'},{label:'Flag',value:'Kazakhstan'},{label:'Encounters',value:'8 / 6 months'},{label:'Open sea',value:'3'}]},
    {id:'khazar-wave',label:'KHAZAR WAVE',subtitle:'Oil tanker · 9 encounters',type:'VESSEL',x:13,y:91,risk:46,details:[{label:'IMO',value:'9261840'},{label:'Flag',value:'Azerbaijan'},{label:'Encounters',value:'9 / 6 months'},{label:'Open sea',value:'7'}]},
    {id:'baku-express',label:'BAKU EXPRESS',subtitle:'Ro-Ro · risk 63',type:'VESSEL',x:37,y:95,risk:63,details:[{label:'IMO',value:'9451188'},{label:'Flag',value:'Azerbaijan'},{label:'Shared calls',value:'12'},{label:'Last proximity',value:'29 Jul 2026'}]},
    {id:'alat',label:'ALAT',subtitle:'Repeated port call',type:'PORT',x:87,y:25,details:[{label:'Calls, 18 months',value:'24'},{label:'Last call',value:'18 Jul 2026'},{label:'Country',value:'Azerbaijan'},{label:'Context',value:'Port proximity only'}]},
    {id:'turkmenbashi',label:'TURKMENBASHI',subtitle:'Historical destination',type:'PORT',x:87,y:75,details:[{label:'Calls, 18 months',value:'19'},{label:'Last call',value:'04 Jul 2026'},{label:'Country',value:'Turkmenistan'},{label:'Context',value:'Completed voyages'}]},
    {id:'company-c',label:'Khazar Shipping LLC',subtitle:'Reported KHAZAR operator',type:'COMPANY',x:63,y:6,details:[{label:'Role',value:'Operator'},{label:'Country',value:'Azerbaijan'},{label:'Fleet',value:'4 vessels'},{label:'Source',value:'Demo registry · REPORTED'}]},
    {id:'cargo-pipes',label:'STEEL PIPES · 3 200 t',subtitle:'Historical declared cargo',type:'CARGO',x:87,y:94,details:[{label:'Status',value:'REPORTED'},{label:'Voyage',value:'CI-2026-129'},{label:'Origin',value:'Alat'},{label:'Destination',value:'Aktau'}]},
    {id:'voy-129',label:'VOYAGE #129',subtitle:'Alat → Aktau · completed',type:'VOYAGE',x:65,y:94,details:[{label:'Started',value:'14 Jul · 06:40'},{label:'Completed',value:'16 Jul · 19:18'},{label:'Distance',value:'421 km'},{label:'Risk',value:'58 / 100'}]},
    {id:'event-route-2801',label:'ОТКЛОНЕНИЕ МАРШРУТА',subtitle:'EV-2801 · 38 км',type:'EVENT',x:35,y:35,details:[{label:'Начало',value:'10 авг · 13:20'},{label:'Место',value:'Центральный Каспий · 41.34°N, 50.75°E'},{label:'Отклонение',value:'38 км'},{label:'Достоверность',value:'94%'}]},
    {id:'event-ais-2802',label:'ПРОПУСК AIS',subtitle:'EV-2802 · 3 ч 15 мин',type:'EVENT',x:42,y:31,details:[{label:'Период',value:'10 авг · 14:10–17:25'},{label:'Последняя позиция',value:'41.89°N, 50.52°E'},{label:'Покрытие',value:'Высокое'},{label:'Достоверность',value:'98%'}]},
    {id:'encounter-884',label:'ВСТРЕЧА EN-884',subtitle:'CASPIAN STAR + TURAN · 174 м',type:'ENCOUNTER',x:28,y:58,details:[{label:'Период',value:'10 авг · 17:28–20:15'},{label:'Место',value:'Центральный Каспий · вне портовых зон'},{label:'Минимальная дистанция',value:'174 м'},{label:'Продолжительность',value:'2 ч 47 мин'}]},
    {id:'event-draught-142',label:'ИЗМЕНЕНИЕ ОСАДКИ',subtitle:'DR-142 · +0.9 м',type:'EVENT',x:60,y:64,details:[{label:'Время',value:'10 авг · 17:40'},{label:'Место',value:'Вне порта · 42.05°N, 50.62°E'},{label:'Изменение',value:'4.1 → 5.0 м'},{label:'Достоверность',value:'96%'}]},
    {id:'event-cargo-143',label:'ГРУЗ / ОСАДКА',subtitle:'ADV-6001 · требует проверки',type:'EVENT',x:64,y:68,details:[{label:'Время расчёта',value:'10 авг · 17:42'},{label:'Груз',value:'5 000 т стали'},{label:'Ожидалось',value:'+1.05–1.30 м'},{label:'Наблюдалось',value:'+0.30 м'}]},
  ],
  edges:[
    {id:'e-encounter',source:'caspian-star',target:'turan',type:'ENCOUNTERED',label:'14 встреч',confidence:'HIGH',priority:'HIGH',explanation:'Суда наблюдались рядом 14 раз за 6 месяцев; 11 встреч произошли в открытом море. Это повторяемость совместного присутствия, а не вывод о характере отношений.',observations:[{label:'Период',value:'6 месяцев'},{label:'Встречи',value:'14'},{label:'В открытом море',value:'11'},{label:'Средняя дистанция',value:'240 м'},{label:'Суммарная длительность',value:'18 ч 42 мин'}],evidence:['EN-884 · встреча 10 авг, 174 м','EN-731 · встреча 22 июл, 310 м','AGG-014 · агрегат 14 наблюдений'],sourceLabel:'AIS encounter engine · агрегированные события',updatedAt:'10 авг, 18:02',dataStatus:'VERIFIED'},
    {id:'e-operator-a',source:'caspian-star',target:'company-a',type:'OPERATED_BY',label:'оператор',confidence:'HIGH',priority:'LOW',explanation:'Оператор указан в профиле судна; запись имеет статус ЗАЯВЛЕНО и требует реестровой верификации.',observations:[{label:'Роль',value:'Оператор'},{label:'Судов в профиле',value:'2'},{label:'Действует с',value:'2023'}],evidence:['REG-KZ-441 · выписка профиля','IMO-9384721 · карточка судна'],sourceLabel:'Демонстрационная корпоративная выписка',updatedAt:'09 авг, 12:20',dataStatus:'REPORTED'},
    {id:'e-owner',source:'caspian-star',target:'owner-a',type:'OWNED_BY',label:'владелец',confidence:'MEDIUM',priority:'MEDIUM',explanation:'Заявленная связь владения получена из демонстрационной корпоративной выписки и требует реестровой верификации.',observations:[{label:'Роль',value:'Заявленный владелец'},{label:'Достоверность',value:'79%'},{label:'Проверка',value:'Ожидается'}],evidence:['REG-KZ-441 · владелец в профиле'],sourceLabel:'Демонстрационная корпоративная выписка',updatedAt:'09 авг, 12:20',dataStatus:'REPORTED'},
    {id:'e-turan-operator',source:'turan',target:'company-b',type:'OPERATED_BY',label:'оператор',confidence:'MEDIUM',priority:'LOW',explanation:'Turan Maritime Services указан как оператор TURAN в демонстрационной корпоративной выписке.',observations:[{label:'Роль',value:'Оператор'},{label:'Достоверность',value:'76%'},{label:'Флот',value:'1 судно'}],sourceLabel:'Демонстрационная корпоративная выписка',updatedAt:'08 авг, 16:45',dataStatus:'REPORTED'},
    {id:'e-baku',source:'voy-001',target:'baku',type:'VISITED',label:'отправление',confidence:'HIGH',priority:'LOW',explanation:'Выход рейса №143 из Баку подтверждён AIS-позицией.',observations:[{label:'Отправление',value:'10 авг · 08:00'},{label:'Позиция',value:'40.37°N, 49.89°E'}],evidence:['AIS-44021 · первая позиция рейса'],sourceLabel:'AIS tracking',updatedAt:'10 авг, 08:01',dataStatus:'VERIFIED'},
    {id:'e-aktau',source:'voy-001',target:'aktau',type:'VISITED',label:'назначение',confidence:'HIGH',priority:'LOW',explanation:'Актау заявлен как порт назначения рейса; прибытие ещё не подтверждено.',observations:[{label:'Расчётное прибытие',value:'11 авг · 15:12'},{label:'Статус',value:'В пути'}],evidence:['VOY-143 · план рейса'],sourceLabel:'Voyage engine',updatedAt:'10 авг, 17:46',dataStatus:'ESTIMATED'},
    {id:'e-cargo',source:'caspian-star',target:'cargo-steel',type:'CARRIED',label:'перевозит',confidence:'HIGH',priority:'MEDIUM',explanation:'5 000 т стали заявлены в портовой декларации; модель осадки показывает расхождение, которое требует проверки.',observations:[{label:'Масса',value:'5 000 т'},{label:'Документ',value:'PORT-BAK-0810-143'},{label:'Осадка',value:'+0.30 м против +1.05–1.30 м'}],evidence:['DR-142 · изменение осадки','PORT-BAK-0810-143 · декларация'],sourceLabel:'Портовая декларация + модель осадки',updatedAt:'10 авг, 17:42',dataStatus:'ESTIMATED'},
    {id:'e-voyage',source:'caspian-star',target:'voy-001',type:'RELATED_TO',label:'текущий рейс',confidence:'HIGH',priority:'HIGH',explanation:'Рейс №143 связан с последовательностью отклонения маршрута, пропуска AIS, встречи и изменения осадки.',observations:[{label:'События',value:'7 значимых'},{label:'Оценка риска',value:'91 / 100'},{label:'Статус',value:'Требует проверки'}],evidence:['EG-441 · группа событий','RISK-143 · оценка 91'],sourceLabel:'Event + Risk engines',updatedAt:'10 авг, 17:46',dataStatus:'VERIFIED'},
    {id:'e-company-link',source:'company-a',target:'company-b',type:'RELATED_TO',label:'контекст встреч',confidence:'MEDIUM',priority:'MEDIUM',explanation:'Компании связаны только через агрегат повторных встреч их судов; это не устанавливает корпоративный контроль.',observations:[{label:'Связанные суда',value:'CASPIAN STAR + TURAN'},{label:'Наблюдений',value:'14'},{label:'Корпоративная связь',value:'Не подтверждена'}],evidence:['AGG-014 · агрегат встреч'],sourceLabel:'Explainable graph correlation',updatedAt:'10 авг, 18:02',dataStatus:'ESTIMATED'},
    {id:'e-wind-encounter',source:'caspian-star',target:'caspian-wind',type:'ENCOUNTERED',label:'8 встреч',confidence:'MEDIUM',priority:'MEDIUM',explanation:'Восемь эпизодов совместного присутствия, преимущественно в портовых подходах. Контекст снижает приоритет по сравнению с открытым морем.',observations:[{label:'Встречи',value:'8'},{label:'В открытом море',value:'3'},{label:'Средняя дистанция',value:'610 м'},{label:'Последняя',value:'02 авг 2026'}],evidence:['AGG-022 · 8 наблюдений','EN-812 · портовый подход'],sourceLabel:'AIS encounter engine',updatedAt:'10 авг, 18:02',dataStatus:'VERIFIED'},
    {id:'e-khazar-encounter',source:'caspian-star',target:'khazar-wave',type:'ENCOUNTERED',label:'9 встреч',confidence:'HIGH',priority:'HIGH',explanation:'Семь из девяти наблюдений произошли вне портовых зон при малой скорости. Последовательность требует просмотра, но не определяет характер взаимодействия.',observations:[{label:'Встречи',value:'9'},{label:'В открытом море',value:'7'},{label:'Средняя дистанция',value:'285 м'},{label:'Суммарно рядом',value:'9 ч 16 мин'}],evidence:['EN-804 · 285 м, 1 ч 14 мин','AGG-026 · 9 наблюдений'],sourceLabel:'AIS encounter engine',updatedAt:'10 авг, 18:02',dataStatus:'VERIFIED'},
    {id:'e-baku-express',source:'caspian-star',target:'baku-express',type:'ENCOUNTERED',label:'4 встречи',confidence:'MEDIUM',priority:'LOW',explanation:'Четыре кратких сближения произошли в портовых районах. Доступный контекст соответствует обычным операциям.',observations:[{label:'Встречи',value:'4'},{label:'В портах',value:'4'},{label:'Средняя дистанция',value:'780 м'}],sourceLabel:'AIS encounter engine',updatedAt:'10 авг, 18:02',dataStatus:'VERIFIED'},
    {id:'e-khazar-operator',source:'khazar-wave',target:'company-c',type:'OPERATED_BY',label:'оператор',confidence:'MEDIUM',priority:'LOW',explanation:'Khazar Shipping LLC заявлен оператором KHAZAR WAVE; запись требует сверки с реестром.',observations:[{label:'Роль',value:'Оператор'},{label:'Достоверность',value:'74%'}],sourceLabel:'Демонстрационная корпоративная выписка',updatedAt:'07 авг, 11:30',dataStatus:'REPORTED'},
    {id:'e-alat-call',source:'caspian-star',target:'alat',type:'VISITED',label:'24 захода',confidence:'HIGH',priority:'LOW',explanation:'За 18 месяцев подтверждено 24 захода в порт Алят.',observations:[{label:'Заходы',value:'24'},{label:'Последний',value:'18 июл 2026'}],sourceLabel:'Port call registry',updatedAt:'10 авг, 06:00',dataStatus:'VERIFIED'},
    {id:'e-turkmenbashi-call',source:'caspian-star',target:'turkmenbashi',type:'VISITED',label:'19 заходов',confidence:'HIGH',priority:'LOW',explanation:'История содержит 19 завершённых рейсов в Туркменбаши.',observations:[{label:'Заходы',value:'19'},{label:'Последний',value:'04 июл 2026'}],sourceLabel:'Port call registry',updatedAt:'10 авг, 06:00',dataStatus:'VERIFIED'},
    {id:'e-voy-129',source:'caspian-star',target:'voy-129',type:'RELATED_TO',label:'исторический рейс',confidence:'HIGH',priority:'MEDIUM',explanation:'Завершённый рейс №129 используется как сопоставимый исторический контекст текущего рейса.',observations:[{label:'Маршрут',value:'Алят → Актау'},{label:'Риск',value:'58 / 100'},{label:'Завершён',value:'16 июл'}],sourceLabel:'Voyage history',updatedAt:'10 авг, 06:00',dataStatus:'VERIFIED'},
    {id:'e-voy-129-cargo',source:'voy-129',target:'cargo-pipes',type:'CARRIED',label:'груз рейса',confidence:'HIGH',priority:'LOW',explanation:'Для рейса №129 заявлено 3 200 т стальных труб.',observations:[{label:'Масса',value:'3 200 т'},{label:'Статус',value:'Заявлено'}],sourceLabel:'Портовая декларация',updatedAt:'16 июл, 19:20',dataStatus:'REPORTED'},
    {id:'e-voy-129-alat',source:'voy-129',target:'alat',type:'VISITED',label:'отправление',confidence:'HIGH',priority:'LOW',explanation:'Отправление рейса №129 из Алята подтверждено AIS и портовым событием.',sourceLabel:'AIS + port events',updatedAt:'14 июл, 06:42',dataStatus:'VERIFIED'},
    {id:'e-voy-129-aktau',source:'voy-129',target:'aktau',type:'VISITED',label:'прибытие',confidence:'HIGH',priority:'LOW',explanation:'Прибытие рейса №129 в Актау подтверждено портовым событием.',sourceLabel:'Port events',updatedAt:'16 июл, 19:20',dataStatus:'VERIFIED'},
    {id:'e-route-event',source:'caspian-star',target:'event-route-2801',type:'RELATED_TO',label:'событие маршрута',confidence:'HIGH',priority:'MEDIUM',explanation:'Событие создано после выхода судна на 38 км за собственный исторический коридор.',observations:[{label:'Дата и время',value:'10 авг · 13:20'},{label:'Место',value:'Центральный Каспий · 41.34°N, 50.75°E'},{label:'Отклонение',value:'38 км'},{label:'Обычно',value:'0–8 км'}],evidence:['EV-2801 · отклонение маршрута','TRACK-143 · наблюдаемый трек'],sourceLabel:'Behavior + Event engines',updatedAt:'10 авг, 13:20',dataStatus:'VERIFIED'},
    {id:'e-ais-event',source:'caspian-star',target:'event-ais-2802',type:'RELATED_TO',label:'пропуск AIS',confidence:'HIGH',priority:'HIGH',explanation:'Позиционные сообщения отсутствовали 3 ч 15 мин в районе с высоким качеством покрытия. Причина отсутствия данных не установлена.',observations:[{label:'Период',value:'10 авг · 14:10–17:25'},{label:'Последняя позиция',value:'41.89°N, 50.52°E'},{label:'Продолжительность',value:'3 ч 15 мин'},{label:'Возможная область',value:'радиус до 72 км'}],evidence:['EV-2802 · пропуск AIS','AIS-RESTORE-1725 · восстановление сигнала'],sourceLabel:'AIS coverage + Event engine',updatedAt:'10 авг, 17:25',dataStatus:'VERIFIED'},
    {id:'e-encounter-event-star',source:'caspian-star',target:'encounter-884',type:'ENCOUNTERED',label:'участник встречи',confidence:'HIGH',priority:'HIGH',explanation:'CASPIAN STAR является участником наблюдаемой встречи EN-884.',observations:[{label:'Период',value:'10 авг · 17:28–20:15'},{label:'Место',value:'Центральный Каспий · вне портовых зон'},{label:'Минимальная дистанция',value:'174 м'},{label:'Продолжительность',value:'2 ч 47 мин'}],evidence:['EN-884 · агрегированные AIS-позиции'],sourceLabel:'AIS encounter engine',updatedAt:'10 авг, 20:16',dataStatus:'VERIFIED'},
    {id:'e-encounter-event-turan',source:'encounter-884',target:'turan',type:'ENCOUNTERED',label:'второй участник',confidence:'HIGH',priority:'HIGH',explanation:'TURAN является вторым участником встречи EN-884; совместное присутствие подтверждено синхронными AIS-позициями.',observations:[{label:'Период',value:'10 авг · 17:28–20:15'},{label:'Место',value:'Центральный Каспий'},{label:'Скорость TURAN',value:'0.4 уз'}],evidence:['EN-884 · синхронные позиции TURAN'],sourceLabel:'AIS encounter engine',updatedAt:'10 авг, 20:16',dataStatus:'VERIFIED'},
    {id:'e-draught-event',source:'caspian-star',target:'event-draught-142',type:'RELATED_TO',label:'изменение осадки',confidence:'HIGH',priority:'MEDIUM',explanation:'После восстановления AIS получено новое значение заявленной осадки вне порта.',observations:[{label:'Дата и время',value:'10 авг · 17:40'},{label:'Место',value:'Вне порта · 42.05°N, 50.62°E'},{label:'До',value:'4.1 м'},{label:'После',value:'5.0 м'}],evidence:['DR-142 · изменение +0.9 м','AIS-STATIC-1740 · новое значение'],sourceLabel:'AIS static data + Event engine',updatedAt:'10 авг, 17:40',dataStatus:'VERIFIED'},
    {id:'e-cargo-event',source:'cargo-steel',target:'event-cargo-143',type:'RELATED_TO',label:'несоответствие модели',confidence:'HIGH',priority:'HIGH',explanation:'Заявленный груз и наблюдаемое изменение осадки отличаются от диапазона модели конкретного судна. Требуется проверка исходных данных.',observations:[{label:'Дата расчёта',value:'10 авг · 17:42'},{label:'Место контекста',value:'Рейс Баку → Актау'},{label:'Ожидалось',value:'+1.05–1.30 м'},{label:'Наблюдалось',value:'+0.30 м'}],evidence:['ADV-6001 · груз / осадка','PORT-BAK-0810-143 · декларация','DR-142 · наблюдение осадки'],sourceLabel:'Cargo + vessel draught model',updatedAt:'10 авг, 17:42',dataStatus:'ESTIMATED'},
  ],
  primaryConnection:{source:'CASPIAN STAR',target:'TURAN',encounters:14,openSea:11,averageDistance:'240 m',totalDuration:'18 ч 42 мин',period:'6 месяцев',strength:'HIGH',explanation:'Повторяющаяся связь основана на агрегированных событиях encounter. Она повышает приоритет проверки только в сочетании с контекстом текущего рейса и не переносит оценку риска одного судна на другое.'},
}

export const aktauPortOperations: AktauPortOperations = {
  updatedAt:'10 авг 2026 · 14:10 UTC+5',
  operationalLoad:68,
  arriving:7,
  inPort:5,
  waiting:3,
  departing:2,
  averageWaiting:'1h 42m',
  berthsAvailable:3,
  berthsOccupied:5,
  highRiskArrivals:1,
  arrivals:[
    {id:'arr-143',portCallId:'pc-aktau-143',vesselId:'caspian-star',vesselName:'CASPIAN STAR',imo:'9384721',reportedEta:'14:30',predictedEta:'15:05',likelyWindow:'14:52–15:18',etaConfidence:87,delayMinutes:35,berth:'#5',cargo:'Steel',cargoMass:'5 000 t',risk:91,status:'ATTENTION',queuePosition:2},
    {id:'arr-212',portCallId:'pc-aktau-212',vesselId:'turan',vesselName:'TURAN',imo:'9217748',reportedEta:'14:15',predictedEta:'14:20',likelyWindow:'14:12–14:31',etaConfidence:91,delayMinutes:5,berth:'#3',cargo:'Grain',cargoMass:'3 400 t',risk:21,status:'NORMAL',queuePosition:1},
    {id:'arr-227',portCallId:'pc-aktau-227',vesselId:'baku-express',vesselName:'BAKU EXPRESS',imo:'9451180',reportedEta:'15:25',predictedEta:'15:40',likelyWindow:'15:29–15:54',etaConfidence:84,delayMinutes:15,berth:'#7',cargo:'General',cargoMass:'2 100 t',risk:14,status:'NORMAL',queuePosition:3},
    {id:'arr-231',portCallId:'pc-aktau-231',vesselId:'caspian-wind',vesselName:'CASPIAN WIND',imo:'9347014',reportedEta:'16:00',predictedEta:'16:10',likelyWindow:'15:57–16:24',etaConfidence:79,delayMinutes:10,berth:'#7',cargo:'Equipment',cargoMass:'1 780 t',risk:19,status:'WAITING',queuePosition:4},
    {id:'arr-238',portCallId:'pc-aktau-238',vesselId:'khazar-wave',vesselName:'KHAZAR WAVE',imo:'9261840',reportedEta:'17:30',predictedEta:'17:36',likelyWindow:'17:22–17:49',etaConfidence:88,delayMinutes:6,berth:'#1',cargo:'Oil products',cargoMass:'7 800 t',risk:28,status:'NORMAL',queuePosition:5},
    {id:'arr-242',portCallId:'pc-aktau-242',vesselId:'volga-marine',vesselName:'VOLGA MARINE',imo:'9142202',reportedEta:'18:10',predictedEta:'18:18',likelyWindow:'18:05–18:31',etaConfidence:86,delayMinutes:8,berth:'#8',cargo:'General',cargoMass:'3 900 t',risk:8,status:'NORMAL',queuePosition:6},
    {id:'arr-247',portCallId:'pc-aktau-247',vesselId:'sea-steppe',vesselName:'SEA STEPPE',imo:'9721046',reportedEta:'19:00',predictedEta:'19:12',likelyWindow:'18:58–19:27',etaConfidence:81,delayMinutes:12,berth:'#10',cargo:'Containers',cargoMass:'4 250 t',risk:11,status:'NORMAL',queuePosition:7},
  ],
  berths:[
    {id:'berth-1',name:'#1',length:210,maxVesselLength:195,maxDraught:8.2,cargoTypes:['Oil products'],equipment:['Loading arms','Pump station'],status:'OCCUPIED',currentVessel:'AKTAU MERCHANT',serviceStarted:'09:10',expectedCompletion:'16:25',nextVessel:'KHAZAR WAVE',availableFrom:'16:40'},
    {id:'berth-2',name:'#2',length:150,maxVesselLength:140,maxDraught:4.5,cargoTypes:['General'],equipment:['Mobile crane'],status:'AVAILABLE',availableFrom:'сейчас',restriction:'Draught ≤ 4.5 m'},
    {id:'berth-3',name:'#3',length:175,maxVesselLength:165,maxDraught:6.8,cargoTypes:['Grain','General'],equipment:['2 × portal crane','Conveyor'],status:'OCCUPIED',currentVessel:'TURAN',serviceStarted:'10:30',expectedCompletion:'14:35',nextVessel:'PORT WORKBOAT',availableFrom:'14:45'},
    {id:'berth-5',name:'#5',length:195,maxVesselLength:180,maxDraught:7.5,cargoTypes:['General','Steel'],equipment:['2 × portal crane','Reach stacker'],status:'OCCUPIED',currentVessel:'TURAN CARRIER',serviceStarted:'10:30',expectedCompletion:'14:35',nextVessel:'CASPIAN STAR',availableFrom:'14:45'},
    {id:'berth-7',name:'#7',length:185,maxVesselLength:170,maxDraught:6.9,cargoTypes:['General','Steel','Equipment'],equipment:['Portal crane','Ro-Ro ramp'],status:'AVAILABLE',availableFrom:'сейчас'},
    {id:'berth-8',name:'#8',length:160,maxVesselLength:150,maxDraught:5.8,cargoTypes:['General'],equipment:['Mobile crane'],status:'OCCUPIED',currentVessel:'KURYK TRADER',serviceStarted:'08:45',expectedCompletion:'18:05',nextVessel:'VOLGA MARINE',availableFrom:'18:20'},
    {id:'berth-9',name:'#9',length:145,maxVesselLength:135,maxDraught:5.0,cargoTypes:['General'],equipment:['Mobile crane'],status:'LIMITED',currentVessel:'SERVICE BARGE',serviceStarted:'11:10',expectedCompletion:'17:30',availableFrom:'17:45',restriction:'Equipment inspection'},
    {id:'berth-10',name:'#10',length:205,maxVesselLength:190,maxDraught:7.2,cargoTypes:['Containers','General'],equipment:['STS crane','Reach stacker'],status:'AVAILABLE',availableFrom:'сейчас'},
  ],
  queue:[
    {position:1,vesselName:'TURAN',eta:'14:20',berth:'#3',cargo:'Grain',priority:'NORMAL',reason:'Berth compatible · earliest operational window'},
    {position:2,vesselName:'CASPIAN STAR',eta:'15:05',berth:'#5',cargo:'Steel',priority:'HIGH',reason:'High-risk pre-arrival review before service'},
    {position:3,vesselName:'BAKU EXPRESS',eta:'15:40',berth:'#7',cargo:'General',priority:'NORMAL',reason:'Moved from #5 to reduce overlap'},
    {position:4,vesselName:'CASPIAN WIND',eta:'16:10',berth:'#7',cargo:'Equipment',priority:'NORMAL',reason:'Queued after BAKU EXPRESS service window'},
  ],
  loadForecast:[
    {offset:'NOW',time:'14:00',load:42,level:'NORMAL'},
    {offset:'+2 HOURS',time:'16:00',load:58,level:'ELEVATED'},
    {offset:'+4 HOURS',time:'18:00',load:74,level:'HIGH'},
    {offset:'+6 HOURS',time:'20:00',load:91,level:'CRITICAL'},
  ],
  recommendation:{
    id:'rec-aktau-701',title:'Перенести BAKU EXPRESS',vesselName:'BAKU EXPRESS',fromBerth:'#5',toBerth:'#7',
    explanation:'Причал #7 совместим с генеральным грузом и свободен до подхода CASPIAN WIND. Перенос снимает пересечение сервисных окон на #5.',
    factors:['ETA 15:40','Berth #7 compatible','Окно #7 свободно','CASPIAN STAR требует #5'],waitingEffect:'−42 min',loadBefore:91,loadAfter:76,status:'PENDING',
  },
  portCall:{
    id:'pc-aktau-143',vesselId:'caspian-star',vesselName:'CASPIAN STAR',imo:'9384721',voyageId:'voy-001',portId:'aktau',status:'APPROACHING',
    reportedEta:'14:30',predictedEta:'15:05',etaWindow:'14:52–15:18',etaConfidence:87,berthId:'berth-5',queuePosition:2,
    cargoType:'Steel',reportedCargo:'5 000 t',verifiedCargo:'4 920 t',reportedDraught:'4.5 m',verifiedDraught:'5.1 m',
    expectedService:'5h 00m',serviceConfidence:82,projectedRelease:'20:05',risk:91,attention:'HIGH',significantEvents:7,
    riskReasons:['Route deviation · 38 km','AIS gap · 3h 15m','Vessel encounter · TURAN','Cargo / draught mismatch','Fuel anomaly'],
    recommendedActions:['Подготовить причал #5','Проверить грузовые документы','Верифицировать осадку','Проверить события текущего рейса'],
    compatibility:[
      {label:'Длина',vessel:'142 m',berth:'≤ 180 m',result:'COMPATIBLE'},
      {label:'Осадка',vessel:'5.0 m',berth:'≤ 7.5 m',result:'COMPATIBLE'},
      {label:'Груз',vessel:'Steel',berth:'General / Steel',result:'COMPATIBLE'},
      {label:'Причал #2',vessel:'Draught 5.0 m',berth:'Max 4.5 m',result:'NOT_COMPATIBLE'},
    ],
    timeline:[
      {id:'pe-1',time:'12:00',type:'VESSEL_APPROACHING',title:'Подход к Актау',detail:'PortCall создан автоматически из активного рейса',status:'ACTUAL'},
      {id:'pe-2',time:'15:05',type:'ETA_CHANGED',title:'Расчётное прибытие',detail:'Вероятное окно 14:52–15:18 · confidence 87%',status:'PREDICTED'},
      {id:'pe-3',time:'15:20',type:'VESSEL_ARRIVED',title:'Фактическое прибытие',detail:'Демо-результат закрытого операционного цикла',status:'ACTUAL'},
      {id:'pe-4',time:'15:35',type:'BERTH_ASSIGNED',title:'Швартовка · причал #5',detail:'Назначение подтверждено диспетчером',status:'ACTUAL'},
      {id:'pe-5',time:'15:50',type:'SERVICE_STARTED',title:'Обработка начата',detail:'Steel · 5 000 t reported',status:'ACTUAL'},
      {id:'pe-6',time:'20:30',type:'SERVICE_COMPLETED',title:'Ожидаемое завершение',detail:'Service model forecast',status:'PREDICTED'},
      {id:'pe-7',time:'20:32',type:'SERVICE_COMPLETED',title:'Фактическое завершение',detail:'Actual service 4h 42m',status:'ACTUAL'},
      {id:'pe-8',time:'21:10',type:'VESSEL_DEPARTED',title:'Выход из порта',detail:'PortCall завершён · feedback опубликован',status:'ACTUAL'},
    ],
    feedback:{predictedEta:'15:05',actualArrival:'15:20',etaError:'+15 min',predictedService:'5h 00m',actualService:'4h 42m',serviceError:'−18 min'},
  },
}
